# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseNotifiction' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirebaseNotifiction
pod 'Firebase/Core', '~> 5.20.1'
pod 'Firebase/Messaging', '~> 5.20.1'

end
